### ISSUE TITLE
Fix Python 3.8.1

### ISSUE THREAD

**Issue by aby2s** [meeshkan/meeshkan#178]

**Comment by aby2s** [comment]
Fix dataclasses dependencies - Done

**Comment by aby2s** [comment]
```
(py38) nikolay@nikolay-dell:~/projects/meeshkan/meeshkan$ meeshkan tutorial
Traceback (most recent call last):
  File "/home/nikolay/.local/bin/meeshkan", line 7, in <module>
    from meeshkan.__main__ import cli
  File "/home/nikolay/projects/meeshkan/meeshkan/meeshkan/__init__.py", line 1, in <module>
    from . import build
  File "/home/nikolay/projects/meeshkan/meeshkan/meeshkan/build/__init__.py", line 3, in <module>
    from .builder import *
  File "/home/nikolay/projects/meeshkan/meeshkan/meeshkan/build/builder.py", line 114
    useable_headers: Mapping[str, str] = { k: v for k,v in exchange.response.headers.items() if k not in ['content-type', 'content-length', 'Content-Type', 'Content-Length'] and isinstance(v, str)}
                   ^
SyntaxError: invalid syntax
```
