### ISSUE TITLE
Recording fails with a proxy

### ISSUE THREAD

**Issue by mikesol** [Meeshkan/meeshkan#49]
When running the following command:

```bash
curl --proxy http://localhost:8000 http://time.jsontest.com
```

I got the following crash in version `0.2.6`

```bash
OSError: [WinError 10022] An invalid argument was supplied
2020-02-18 17:12:43,346 - meeshkan.server.proxy.channel - DEBUG - [('::1', 58277, 0, 0)] Trying to flush incomplete data, request "{'method': 'get', 'host': 'time.jsontest.com', 'path': '/', 'pathname': '/', 'protocol': 'http', 'query': {}, 'body': '', 'bodyAsJson': {}, 'headers': {'Host': 'time.jsontest.com', 'User-Agent': 'curl/7.66.0', 'Accept': '*/*', 'Proxy-Connection': 'Keep-Alive'}}", response chunks 0
2020-02-18 17:12:43,356 - tornado.application - ERROR - Uncaught exception, closing connection.
Traceback (most recent call last):
  File "c:\users\mikesolomon\devel\meeshkan-test\.venv\lib\site-packages\tornado\iostream.py", line 752, in wrapper
    return callback(*args)
  File "c:\users\mikesolomon\devel\meeshkan-test\.venv\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "c:\users\mikesolomon\devel\meeshkan-test\.venv\lib\site-packages\meeshkan\server\proxy\channel.py", line 234, in on_server_connect
    self._server_stream.on_connect(self.on_server_read)
AttributeError: 'NoneType' object has no attribute 'on_connect'     
2020-02-18 17:12:43,360 - tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 
0x000001AC9095DD08>)
Traceback (most recent call last):
  File "c:\users\mikesolomon\devel\meeshkan-test\.venv\lib\site-packages\tornado\ioloop.py", line 758, in _run_callback
    ret = callback()
  File "c:\users\mikesolomon\devel\meeshkan-test\.venv\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "c:\users\mikesolomon\devel\meeshkan-test\.venv\lib\site-packages\tornado\iostream.py", line 752, in wrapper
    return callback(*args)
  File "c:\users\mikesolomon\devel\meeshkan-test\.venv\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "c:\users\mikesolomon\devel\meeshkan-test\.venv\lib\site-packages\meeshkan\server\proxy\channel.py", line 234, in on_server_connect
    self._server_stream.on_connect(self.on_server_read)
```

**Comment by mikesol** [comment]
Will close this, as the issue was on my end in trying to use Meeshkan as a proxy. This is not yet possible.
